import ReduxProvider from "@/redux/provider"
import "../global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
      <body>{children}</body>
      {children}</ReduxProvider>
    </html>
  )
}
